version: '2'
services:
    mrp-app:
        image: mrp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mrp-postgresql:5432/mrp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mrp-postgresql:
        extends:
            file: postgresql.yml
            service: mrp-postgresql
